In [2]:
#Q1
import numpy as np
#a
np.random.seed(50)
#b
array = np.random.randint(5, 57, size = (8, 6))
array

array([[53, 37, 16, 50, 38, 35],
       [ 9, 11, 42, 11, 27, 50],
       [10,  7, 36, 12, 52,  9],
       [19, 40, 33, 32, 31, 31],
       [11, 25, 48, 36, 54, 26],
       [47, 46,  5, 11, 24,  7],
       [20, 35, 46, 40, 31,  7],
       [17, 37,  8,  7, 15, 53]])

In [3]:
#c
array[1, 2]

42

In [10]:
#d
array2 = array[:,5]
array2

array([35, 50,  9, 31, 26,  7,  7, 53])

In [11]:
array2 = array2[::-1]
array2

array([53,  7,  7, 26, 31,  9, 50, 35])

In [12]:
#e
array3 = np.max(array, axis = 0)
array3

array([53, 46, 48, 50, 54, 53])

In [13]:
#f
array3_reshaped = array.reshape(1,48)
array3_reshaped

array([[53, 37, 16, 50, 38, 35,  9, 11, 42, 11, 27, 50, 10,  7, 36, 12,
        52,  9, 19, 40, 33, 32, 31, 31, 11, 25, 48, 36, 54, 26, 47, 46,
         5, 11, 24,  7, 20, 35, 46, 40, 31,  7, 17, 37,  8,  7, 15, 53]])

In [32]:
#Q2
import pandas as pd
#a
data = pd.read_csv("/Users/kevin/Downloads/AD 450/mpg.csv")
data.head(10)



manufacturer       model  displ  year  cyl       trans drv  cty  hwy fl  \
0         audi          a4    1.8  1999    4    auto(l5)   f   18   29  p   
1         audi          a4    1.8  1999    4  manual(m5)   f   21   29  p   
2         audi          a4    2.0  2008    4  manual(m6)   f   20   31  p   
3         audi          a4    2.0  2008    4    auto(av)   f   21   30  p   
4         audi          a4    2.8  1999    6    auto(l5)   f   16   26  p   
5         audi          a4    2.8  1999    6  manual(m5)   f   18   26  p   
6         audi          a4    3.1  2008    6    auto(av)   f   18   27  p   
7         audi  a4 quattro    1.8  1999    4  manual(m5)   4   18   26  p   
8         audi  a4 quattro    1.8  1999    4    auto(l5)   4   16   25  p   
9         audi  a4 quattro    2.0  2008    4  manual(m6)   4   20   28  p   

     class  
0  compact  
1  compact  
2  compact  
3  compact  
4  compact  
5  compact  
6  compact  
7  compact  
8  compact  
9  compact

In [19]:
#b
hwy = np.array(data["hwy"]) 
hwy

array([29, 29, 31, 30, 26, 26, 27, 26, 25, 28, 27, 25, 25, 25, 25, 24, 25,
       23, 20, 15, 20, 17, 17, 26, 23, 26, 25, 24, 19, 14, 15, 17, 27, 30,
       26, 29, 26, 24, 24, 22, 22, 24, 24, 17, 22, 21, 23, 23, 19, 18, 17,
       17, 19, 19, 12, 17, 15, 17, 17, 12, 17, 16, 18, 15, 16, 12, 17, 17,
       16, 12, 15, 16, 17, 15, 17, 17, 18, 17, 19, 17, 19, 19, 17, 17, 17,
       16, 16, 17, 15, 17, 26, 25, 26, 24, 21, 22, 23, 22, 20, 33, 32, 32,
       29, 32, 34, 36, 36, 29, 26, 27, 30, 31, 26, 26, 28, 26, 29, 28, 27,
       24, 24, 24, 22, 19, 20, 17, 12, 19, 18, 14, 15, 18, 18, 15, 17, 16,
       18, 17, 19, 19, 17, 29, 27, 31, 32, 27, 26, 26, 25, 25, 17, 17, 20,
       18, 26, 26, 27, 28, 25, 25, 24, 27, 25, 26, 23, 26, 26, 26, 26, 25,
       27, 25, 27, 20, 20, 19, 17, 20, 17, 29, 27, 31, 31, 26, 26, 28, 27,
       29, 31, 31, 26, 26, 27, 30, 33, 35, 37, 35, 15, 18, 20, 20, 22, 17,
       19, 18, 20, 29, 26, 29, 29, 24, 44, 29, 26, 29, 29, 29, 29, 23, 24,
       44, 41, 29, 26, 28

In [21]:
#c
hwy.size

234

In [22]:
#d
hwy.min()

12

In [23]:
np.percentile(hwy, 75)

27.0

In [24]:
hwy.mean()

23.44017094017094

In [29]:
#e
np.sum(hwy > (hwy.mean()))

129

In [31]:
#f
hwy_reverse = hwy[::-1]
hwy_reverse

array([26, 26, 26, 29, 28, 29, 29, 29, 28, 26, 29, 41, 44, 24, 23, 29, 29,
       29, 29, 26, 29, 44, 24, 29, 29, 26, 29, 20, 18, 19, 17, 22, 20, 20,
       18, 15, 35, 37, 35, 33, 30, 27, 26, 26, 31, 31, 29, 27, 28, 26, 26,
       31, 31, 27, 29, 17, 20, 17, 19, 20, 20, 27, 25, 27, 25, 26, 26, 26,
       26, 23, 26, 25, 27, 24, 25, 25, 28, 27, 26, 26, 18, 20, 17, 17, 25,
       25, 26, 26, 27, 32, 31, 27, 29, 17, 19, 19, 17, 18, 16, 17, 15, 18,
       18, 15, 14, 18, 19, 12, 17, 20, 19, 22, 24, 24, 24, 27, 28, 29, 26,
       28, 26, 26, 31, 30, 27, 26, 29, 36, 36, 34, 32, 29, 32, 32, 33, 20,
       22, 23, 22, 21, 24, 26, 25, 26, 17, 15, 17, 16, 16, 17, 17, 17, 19,
       19, 17, 19, 17, 18, 17, 17, 15, 17, 16, 15, 12, 16, 17, 17, 12, 16,
       15, 18, 16, 17, 12, 17, 17, 15, 17, 12, 19, 19, 17, 17, 18, 19, 23,
       23, 21, 22, 17, 24, 24, 22, 22, 24, 24, 26, 29, 26, 30, 27, 17, 15,
       14, 19, 24, 25, 26, 23, 26, 17, 17, 20, 15, 20, 23, 25, 24, 25, 25,
       25, 25, 27, 28, 25